[project]
name = "telegram-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anyio<4.11",
    "chainlit>=2.11.1",
    "ddgs>=9.15.0",
    "faster-whisper>=1.2.1",
    "langchain-core>=1.6.0",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "markdown-it-py>=4.2.0",
    "nvidia-cublas-cu12>=12.9.2.10",
    "nvidia-cuda-runtime-cu12>=12.9.79",
    "nvidia-cudnn-cu12>=9.24.0.43",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-telegram-bot>=22.8",
    "sqlite-vec>=0.1.9",
    "tzdata>=2026.3",
]
